version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: Database1
        restart: always
        environment:
            MONGO_INITDB_DATABASE: db1
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro